[package]
name = "bustubrust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4.0.2"
libc = "0.2.113"

[[bin]]
name= "play"
path = "play/main.rs"

[[bin]]
name= "bpm"
path = "src/main.rs"
